<?php

namespace Rudak\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository
{
    public function getGalleryById($id)
    {
        $qb = $this->createQueryBuilder('g')
            ->addSelect('p')
            ->leftJoin('g.pictures', 'p')
            ->where('g.public = :public')->setParameter('public', true)
            ->andWhere('g.id = :id')->setParameter('id', $id)
            ->getQuery();
        return $qb->getOneOrNullResult();
    }

    public function getAllGalleriesForIndex()
    {
        $qb = $this->createQueryBuilder('g')
            ->addSelect('p')
            ->leftJoin('g.pictures', 'p')
            ->orderBy('g.public', 'DESC')
            ->addOrderBy('g.id', 'desc')
            ->getQuery();
        return $qb->execute();
    }
}
